collections:
  topics:
    output: true

defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topics"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
